
"""
Outbreak of Lies - Rumour Spread Simulator
==========================================

Simulates stochastic rumour propagation through a NetworkX social network.

Features:
- Configurable transmission probability.
- Multiple simulation rounds.
- Optional blocked users for intervention experiments.
- Reproducible simulations using random seeds.
- Cumulative spread history.
- Validation of inputs.
- Detailed results for evaluation and visualization.

Blocked users cannot receive or transmit the rumour in this model.
This is a simulation assumption, not an action on real social accounts.
"""

import random
from numbers import Real


def simulate_spread(
    graph,
    source,
    transmission_prob=0.3,
    blocked_nodes=None,
    max_rounds=50,
    seed=None,
):
    """
    Simulate rumour spreading through a social network.

    Parameters
    ----------
    graph : networkx.Graph
        Social network generated by generate_network().
    source : int or hashable
        User ID where the rumour originates.
    transmission_prob : float, default=0.3
        Probability that an infected user infects each susceptible neighbour.
        Must be between 0.0 and 1.0.
    blocked_nodes : iterable, optional
        User IDs prevented from receiving and transmitting the rumour.
    max_rounds : int, default=50
        Maximum number of propagation rounds.
    seed : int, optional
        Random seed for reproducible simulation results.

    Returns
    -------
    dict
        infected_users:
            Sorted list of users who received the rumour.
        final_reach:
            Total number of users infected by the end.
        spread_history:
            Cumulative number of infected users after each round.
        rounds:
            Number of rounds actually simulated.
        source:
            Starting user ID.
        blocked_nodes:
            Sorted list of blocked user IDs.
        transmission_prob:
            Probability used for each transmission attempt.
        reached_fraction:
            Fraction of all network users reached.
        stopped_reason:
            Why the simulation ended.

    Notes
    -----
    This is a susceptible-infected (SI) model. Infected users remain
    infected for the rest of the simulation. Each infected user attempts
    to infect each susceptible neighbour once. Newly infected users start
    spreading in the following round.
    """

    # ---------------------------------------------------------
    # 1. Validate the graph
    # ---------------------------------------------------------
    if graph is None or not callable(getattr(graph, "neighbors", None)):
        raise TypeError(
            "graph must be a NetworkX graph with a neighbors() method."
        )

    if graph.number_of_nodes() == 0:
        raise ValueError("graph must contain at least one user.")

    if source not in graph:
        raise ValueError(
            f"Source user {source!r} does not exist in the graph."
        )

    # ---------------------------------------------------------
    # 2. Validate transmission probability
    # ---------------------------------------------------------
    if (
        isinstance(transmission_prob, bool)
        or not isinstance(transmission_prob, Real)
        or not 0.0 <= transmission_prob <= 1.0
    ):
        raise ValueError(
            "transmission_prob must be a number between 0.0 and 1.0."
        )

    # ---------------------------------------------------------
    # 3. Validate maximum rounds
    # ---------------------------------------------------------
    if (
        isinstance(max_rounds, bool)
        or not isinstance(max_rounds, int)
        or max_rounds < 0
    ):
        raise ValueError(
            "max_rounds must be a non-negative integer."
        )

    # ---------------------------------------------------------
    # 4. Validate and normalize blocked users
    # ---------------------------------------------------------
    if blocked_nodes is None:
        blocked = set()
    else:
        try:
            blocked = set(blocked_nodes)
        except TypeError as exc:
            raise TypeError(
                "blocked_nodes must be an iterable of user IDs."
            ) from exc

    unknown_nodes = blocked - set(graph.nodes)

    if unknown_nodes:
        raise ValueError(
            f"blocked_nodes contains users not in the graph: "
            f"{unknown_nodes!r}"
        )

    # ---------------------------------------------------------
    # 5. Initialize the random generator
    # ---------------------------------------------------------
    rng = random.Random(seed)

    total_users = graph.number_of_nodes()

    # If the rumour starts at a blocked user, it cannot spread.
    if source in blocked:
        return {
            "infected_users": [],
            "final_reach": 0,
            "spread_history": [0],
            "rounds": 0,
            "source": source,
            "blocked_nodes": sorted(blocked, key=str),
            "transmission_prob": float(transmission_prob),
            "reached_fraction": 0.0,
            "stopped_reason": "source_blocked",
        }

    # ---------------------------------------------------------
    # 6. Set initial infection state
    # ---------------------------------------------------------
    infected = {source}

    # Only users infected in the current round spread the rumour.
    active = {source}

    # Index 0 represents the initial state, before any spread.
    spread_history = [1]

    rounds = 0

    if max_rounds == 0:
        stopped_reason = "max_rounds"
    else:
        stopped_reason = "no_new_infections"

    # ---------------------------------------------------------
    # 7. Simulate spread round by round
    # ---------------------------------------------------------
    while active and rounds < max_rounds:
        newly_infected = set()

        for user in active:
            for neighbour in graph.neighbors(user):

                # A user already infected cannot be infected again.
                if neighbour in infected:
                    continue

                # Blocked users cannot receive the rumour.
                if neighbour in blocked:
                    continue

                # Attempt transmission independently for each edge.
                if rng.random() < transmission_prob:
                    newly_infected.add(neighbour)

        # Apply all new infections together at the end of the round.
        infected.update(newly_infected)

        # Only newly infected users spread in the next round.
        active = newly_infected

        rounds += 1
        spread_history.append(len(infected))

        if not active:
            stopped_reason = "no_new_infections"
            break
    else:
        if rounds >= max_rounds and active:
            stopped_reason = "max_rounds"
        elif not active:
            stopped_reason = "no_new_infections"

    # ---------------------------------------------------------
    # 8. Calculate final metrics
    # ---------------------------------------------------------
    final_reach = len(infected)
    reached_fraction = final_reach / total_users

    # ---------------------------------------------------------
    # 9. Return results in a consistent format
    # ---------------------------------------------------------
    return {
        "infected_users": sorted(infected, key=str),
        "final_reach": final_reach,
        "spread_history": spread_history,
        "rounds": rounds,
        "source": source,
        "blocked_nodes": sorted(blocked, key=str),
        "transmission_prob": float(transmission_prob),
        "reached_fraction": reached_fraction,
        "stopped_reason": stopped_reason,
    }
